pipeline:
  deploy:
    image: cschlosser/drone-ftps
    hostname: wla1.wndp.pt:21
    secrets: [ ftp_username, ftp_password ]
    secure: false
    dest_dir: /public_html/
    src_dir: /
    exclude:
      - ^\.git/$
      - ^\.gitignore$
      - ^\.drone.yml$